### ISSUE TITLE
AVS response time

### ISSUE THREAD

**Issue by dly9014** [sammachin/AlexaCHIP#10]
Hi Sam, like so many others I really appreciate your project. I've built it twice now on different gen RPIs.   For my use case I have alexa respond to the push of an IoT button. Unfortunately response time is 5-10 sec, sometimes longer. I asked a question on the dev forum (https://forums.developer.amazon.com/questions/30086/streaming-audio-to-avs-to-improve-unacceptable-res.html), and amazon replied with help on how to do this, but it will probably take me weeks to figure it out. I was wondering if you might consider modifying your alexa function in main.py to enable chunked streaming vs file input to AVS.  It would benefit so many of us hobbyists out there. I will be trying to figure it out, but my python skills are at a beginner level. Thanks again for your project!

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
