### ISSUE TITLE
Errors on running setup_gpio.sh

### ISSUE THREAD

**Issue by curiousmint** [sammachin/AlexaCHIP#11]
Hi Sam,

Thanks for taking this project on and devoting your time to it - it is much appreciated!

I ran though your setup guide and am stuck on trying to setup the gpio pins. Here are the errors I get:

```
409
tee:  /sys/class/gpio/export: Invalid argument
cat:  /sys/class/gpio/gpio409/direction: No such file or directory
cat:  /sys/class/gpio/gpio409/value: No such file or directory
```

If I run the main.py skipping the gpio setup, I receive this error:

```
Traceback (most recent call last):
    File "main.py", line 12, in <module>
        from memcache import Client
ImportError: No module named memcache
```

Running apt-get install memcached tells me that I already have the latest version.

Do you have any ideas on how I could proceed?

**Comment by kellzey** [comment]
Read this... 

http://docs.getchip.com/chip.html#gpio

And follow the section about Kernel version and bases for the expander pins...

My gpio folders were /gpio1016/ instead of /gpio409/ as referenced in the gpio_setup script.  just edit the script and change to 1016

This gpio409 is also referened in the main.py  file.  Just edit and replace.  There is one reference.

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
