### ISSUE TITLE
Kernel4.4 Error on running main.py

### ISSUE THREAD

**Issue by vargai** [sammachin/AlexaCHIP#13]
Hello Sam,

I run main.py then Alexa says hello and the script crashes. I use a microsoft lifecam vx 700 webcam as mic. I edited /etc/asound.conf and usr/share/alsa/alsa.conf file as it is in the project's description. 

I verified the card number (1) and the device number (0). It is running kernel version 4.4 Jessie.
I can save and play audio with arecord/aplay but when I run python main.py I get this error:

> ALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usable
> Traceback (most recent call last):
>   File "main.py", line 126, in <module>
>     inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL)
> alsaaudio.ALSAAudioError: Invalid argument [default]

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
