### ISSUE TITLE
Main.py never printing ready

### ISSUE THREAD

**Issue by bthuilot** [sammachin/AlexaCHIP#14]
Alexa says "hello" but then it never prints ready to the console and pressing the button and saying commands doesn't work either, and when i cancel the script it says:

Traceback (most recent call last):
     File "main.py", line 112, in <module>
      val = f.read().strip('\n')
KeyboardInterrupt

**Comment by TateFleming** [comment]
Did you ever resolve this problem??

**Comment by renekliment** [comment]
@TateFleming If you are having issues with this repo, please try the new one: https://github.com/alexa-pi/AlexaPi Thank you.

**Comment by TateFleming** [comment]
Does that installation setup work for a CHIP?

**Comment by renekliment** [comment]
@TateFleming Yes. Check out https://github.com/alexa-pi/AlexaPi/wiki/Devices#chip-computer and other parts of the documentation.

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
