### ISSUE TITLE
Support for wake word?

### ISSUE THREAD

**Issue by petabite** [sammachin/AlexaCHIP#18]
Are you guys going to add support for the wake word "Alexa"? On the official amazon instructions, it says that the wake word is now added.

**Comment by renekliment** [comment]
Support for wake word is in the new repo https://github.com/alexa-pi/AlexaPi

Amazon's own sample app is different from ours and has nothing to do with it.

**Comment by petabite** [comment]
Alrighty. Thanks a lot.
