### ISSUE TITLE
After initial response, Alexa will not take further action. 

### ISSUE THREAD

**Issue by PantherTheCat** [sammachin/AlexaCHIP#5]
So not sure how this should work or if it will.
For instance if you ask alexa to read you the shopping list, she will say "Here are the 5 most recent items" and then the interaction ends, before she lists the items. 

The same is true if she calls another service, like Audible - If you ask her to play a book, she will recite the title and information of the book, and then the audio stops. 
Same if you ask her to read one of the Kindle Books. The interaction stops after she responds to the the initial request. 

Any thoughts/ways this can be expanded? Does this work on the PI version?

**Comment by lennysh** [comment]
This does not work on the Pi version, but it is one of the thing's I personally am looking into.  I've already started a .Net version of this for Windows machines, and I will be using the knowledge I learn there on how the system works to try and help fix this Python version. It's not going to be hard to get things like the shopping list and to-do list to work (already have those working as well in my .Net version), but the audio is slightly more complicated as you have to keep updating the service with the current status of the audio stream.  Not to mention each song is a separate stream, and you have to keep requesting the next stream (my .Net version can already stream the first song).

Just trust that these upgrades are being looked into...  :)

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
