### ISSUE TITLE
[Enhancement] Improve the setup guide + Bringing up to par with AlexaPi

### ISSUE THREAD

**Issue by felixekman** [sammachin/AlexaCHIP#6]
Two things to bring the AlexaCHIP version up to par with the AlexaPi. Is there a possibility to bring up the CHIP version to par with the Pi version in terms of LED and internet check routine? 
Also would be great if the installation guide would address audio configurations, how to use the pin's to connect a speaker and microphone or how to use a USB Sound Card, both in regards to connection and in software,

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
